### ISSUE TITLE
dispatch not linked as a dependency

### ISSUE THREAD

**Issue by rezahussain** [Zig1375/MySQL#1]
hello, tried to compile it into my program:

/home/admin2/Desktop/R1Importer/Packages/MySQL-1.2.5/Sources/MySQL/Core/Pool/Pool.swift:2:8: error: no such module 'Dispatch'
import Dispatch
       ^
<unknown>:0: error: build had 1 command failures
error: exit(1): /home/admin2/swift-DEVELOPMENT-SNAPSHOT-2016-04-12-a-ubuntu15.10/usr/bin/swift-build-tool -f /home/admin2/Desktop/R1Importer/.build/debug.yaml default
admin2@ubuntu:~/Desktop/R1Importer/Sources$

**Comment by Zig1375** [comment]
Sorry, I forgot to update readme file..
To install libdispatch:

``` bash
git clone -b experimental/foundation https://github.com/apple/swift-corelibs-libdispatch.git
cd swift-corelibs-libdispatch
git submodule init
git submodule update
sh ./autogen.sh
./configure --with-swift-toolchain=/usr --prefix=/usr
make && sudo make install
```

**Comment by rezahussain** [comment]
Thanks, I got this far:

admin2@ubuntu:~/Desktop/R1Importer$ cd Sources/
admin2@ubuntu:~/Desktop/R1Importer/Sources$ swift build
Compile Swift Module 'MySQL' (13 sources)
<unknown>:0: error: module 'Dispatch' requires feature 'blocks'
<unknown>:0: error: could not build Objective-C module 'Dispatch'
<unknown>:0: error: module 'Dispatch' requires feature 'blocks'
<unknown>:0: error: could not build Objective-C module 'Dispatch'
<unknown>:0: error: module 'Dispatch' requires feature 'blocks'
<unknown>:0: error: could not build Objective-C module 'Dispatch'
<unknown>:0: error: module 'Dispatch' requires feature 'blocks'
<unknown>:0: error: could not build Objective-C module 'Dispatch'
<unknown>:0: error: module 'Dispatch' requires feature 'blocks'
<unknown>:0: error: could not build Objective-C module 'Dispatch'
<unknown>:0: error: module 'Dispatch' requires feature 'blocks'
<unknown>:0: error: could not build Objective-C module 'Dispatch'
<unknown>:0: error: module 'Dispatch' requires feature 'blocks'
<unknown>:0: error: could not build Objective-C module 'Dispatch'
<unknown>:0: error: module 'Dispatch' requires feature 'blocks'
<unknown>:0: error: could not build Objective-C module 'Dispatch'
<unknown>:0: error: build had 1 command failures
error: exit(1): /home/admin2/swift-DEVELOPMENT-SNAPSHOT-2016-04-25-a-ubuntu15.10/usr/bin/swift-build-tool -f /home/admin2/Desktop/R1Importer/.build/debug.yaml

Then I did this: 

swift build -Xcc -fblocks -Xlinker -ldispatch

admin2@ubuntu:~/Desktop/R1Importer/Sources$ swift build -Xcc -fblocks -Xlinker -ldispatch
Compile Swift Module 'MySQL' (13 sources)
/home/admin2/Desktop/R1Importer/Packages/MySQL-1.2.5/Sources/MySQL/Helper/String.swift:6:74: error: type 'NSRegularExpressionOptions' has no member 'CaseInsensitive'
        let regex = try! NSRegularExpression(pattern: pattern, options: .CaseInsensitive);
                                                                         ^~~~~~~~~~~~~~~
/home/admin2/Desktop/R1Importer/Packages/MySQL-1.2.5/Sources/MySQL/Core/Parameters.swift:94:23: error: value of type 'NSDateFormatter' has no member 'stringFromDate'
        values[key] = formatter.stringFromDate(value);
                      ^~~~~~~~~ ~~~~~~~~~~~~~~
<unknown>:0: error: build had 1 command failures
error: exit(1): /home/admin2/swift-DEVELOPMENT-SNAPSHOT-2016-04-25-a-ubuntu15.10/usr/bin/swift-build-tool -f /home/admin2/Desktop/R1Importer/.build/debug.yaml

**Comment by Zig1375** [comment]
I fix it tomorrow..
This version work on swift-DEVELOPMENT-SNAPSHOT-2016-04-12-a

**Comment by rezahussain** [comment]
got it i'll try out 4-12

thanks again

**Comment by Zig1375** [comment]
Now supported swift at April 25, 2016

Tag 1.3.0
        .Package(url: "https://github.com/Zig1375/MySQL.git", majorVersion: 1, minor: 3)
