### ISSUE TITLE
Compiler error

### ISSUE THREAD

**Issue by rezahussain** [Zig1375/MySQL#3]
Hello, I can't seem to compile this project anymore, do you have any tips?

I installed libdispatch from the apple git, included installed the libmysqldev through apt-get, and included the dependency in my package.swift, but it seems I am missing something.

Ubuntu 15.10, mysql 5.6

admin2@admin2:~/Desktop/RS1DataPreparer$ swift build -Xcc -fblocks -Xlinker -ldispatch -v
/home/admin2/swift-DEVELOPMENT-SNAPSHOT-2016-06-06-a-ubuntu15.10/usr/bin/swiftc --driver-mode=swift -I /home/admin2/swift-DEVELOPMENT-SNAPSHOT-2016-06-06-a-ubuntu15.10/usr/lib/swift/pm -L /home/admin2/swift-DEVELOPMENT-SNAPSHOT-2016-06-06-a-ubuntu15.10/usr/lib/swift/pm -lPackageDescription /home/admin2/Desktop/RS1DataPreparer/Package.swift -fileno 3
/usr/bin/git -C /home/admin2/Desktop/RS1DataPreparer/Packages/CMySQL-1.0.0 config --get remote.origin.url
/usr/bin/git -C /home/admin2/Desktop/RS1DataPreparer/Packages/SwiftMySQL-1.5.5 config --get remote.origin.url
/home/admin2/swift-DEVELOPMENT-SNAPSHOT-2016-06-06-a-ubuntu15.10/usr/bin/swiftc --driver-mode=swift -I /home/admin2/swift-DEVELOPMENT-SNAPSHOT-2016-06-06-a-ubuntu15.10/usr/lib/swift/pm -L /home/admin2/swift-DEVELOPMENT-SNAPSHOT-2016-06-06-a-ubuntu15.10/usr/lib/swift/pm -lPackageDescription /home/admin2/Desktop/RS1DataPreparer/Packages/SwiftMySQL-1.5.5/Package.swift -fileno 3
/home/admin2/swift-DEVELOPMENT-SNAPSHOT-2016-06-06-a-ubuntu15.10/usr/bin/swiftc --driver-mode=swift -I /home/admin2/swift-DEVELOPMENT-SNAPSHOT-2016-06-06-a-ubuntu15.10/usr/lib/swift/pm -L /home/admin2/swift-DEVELOPMENT-SNAPSHOT-2016-06-06-a-ubuntu15.10/usr/lib/swift/pm -lPackageDescription /home/admin2/Desktop/RS1DataPreparer/Packages/CMySQL-1.0.0/Package.swift -fileno 3
/home/admin2/swift-DEVELOPMENT-SNAPSHOT-2016-06-06-a-ubuntu15.10/usr/bin/swift-build-tool -f /home/admin2/Desktop/RS1DataPreparer/.build/debug.yaml -v
'/home/admin2/swift-DEVELOPMENT-SNAPSHOT-2016-06-06-a-ubuntu15.10/usr/bin/swiftc' -Xlinker -ldispatch -Xcc -fblocks -Xlinker '-rpath=$ORIGIN' -g '-L/home/admin2/Desktop/RS1DataPreparer/.build/debug' -o '/home/admin2/Desktop/RS1DataPreparer/.build/debug/R1DataPreparer' -emit-executable '/home/admin2/Desktop/RS1DataPreparer/.build/debug/R1DataPreparer.build/Utility.swift.o' '/home/admin2/Desktop/RS1DataPreparer/.build/debug/R1DataPreparer.build/Normalizer.swift.o' '/home/admin2/Desktop/RS1DataPreparer/.build/debug/R1DataPreparer.build/RHTime.swift.o' '/home/admin2/Desktop/RS1DataPreparer/.build/debug/R1DataPreparer.build/dataBlockBuilder.swift.o' '/home/admin2/Desktop/RS1DataPreparer/.build/debug/R1DataPreparer.build/StockData.swift.o' '/home/admin2/Desktop/RS1DataPreparer/.build/debug/R1DataPreparer.build/Config.swift.o' '/home/admin2/Desktop/RS1DataPreparer/.build/debug/R1DataPreparer.build/Scorer.swift.o' '/home/admin2/Desktop/RS1DataPreparer/.build/debug/R1DataPreparer.build/main.swift.o' '/home/admin2/Desktop/RS1DataPreparer/.build/debug/SwiftMySQL.build/Helper/String.swift.o' '/home/admin2/Desktop/RS1DataPreparer/.build/debug/SwiftMySQL.build/Helper/MysqlValue.swift.o' '/home/admin2/Desktop/RS1DataPreparer/.build/debug/SwiftMySQL.build/Helper/Thread.swift.o' '/home/admin2/Desktop/RS1DataPreparer/.build/debug/SwiftMySQL.build/Core/MysqlDebug.swift.o' '/home/admin2/Desktop/RS1DataPreparer/.build/debug/SwiftMySQL.build/Core/MySQLError.swift.o' '/home/admin2/Desktop/RS1DataPreparer/.build/debug/SwiftMySQL.build/Core/Parameters.swift.o' '/home/admin2/Desktop/RS1DataPreparer/.build/debug/SwiftMySQL.build/Core/Pool/Pool.swift.o' '/home/admin2/Desktop/RS1DataPreparer/.build/debug/SwiftMySQL.build/Core/Pool/PoolConnection.swift.o' '/home/admin2/Desktop/RS1DataPreparer/.build/debug/SwiftMySQL.build/Core/Pool/AutoPool.swift.o' '/home/admin2/Desktop/RS1DataPreparer/.build/debug/SwiftMySQL.build/Core/Result/Field.swift.o' '/home/admin2/Desktop/RS1DataPreparer/.build/debug/SwiftMySQL.build/Core/Result/Result.swift.o' '/home/admin2/Desktop/RS1DataPreparer/.build/debug/SwiftMySQL.build/Core/Connection/ConnectionState.swift.o' '/home/admin2/Desktop/RS1DataPreparer/.build/debug/SwiftMySQL.build/Core/Connection/ConnectionConfig.swift.o' '/home/admin2/Desktop/RS1DataPreparer/.build/debug/SwiftMySQL.build/Core/Connection/Connection.swift.o'
/home/admin2/Desktop/RS1DataPreparer/Sources/Normalizer.swift:197: error: undefined reference to '_TMaC5MySQL10Connection'
/home/admin2/Desktop/RS1DataPreparer/Sources/Normalizer.swift:197: error: undefined reference to '_TFC5MySQL10ConnectionCfT6configCS_16ConnectionConfig_S0_'
/home/admin2/Desktop/RS1DataPreparer/Sources/Normalizer.swift:227: error: undefined reference to '_TIFC5MySQL10Connection5queryFzT3sqlSS6valuesGSqGSaGSqSS____CS_6ResultA0_'
/home/admin2/Desktop/RS1DataPreparer/Sources/Normalizer.swift:231: error: undefined reference to '_TMV5MySQL5Value'
/home/admin2/Desktop/RS1DataPreparer/Sources/Normalizer.swift:231: error: undefined reference to '_TFV5MySQL5Valueg6doubleGSqSd_'
/home/admin2/Desktop/RS1DataPreparer/Sources/Normalizer.swift:232: error: undefined reference to '_TMV5MySQL5Value'
/home/admin2/Desktop/RS1DataPreparer/Sources/Normalizer.swift:232: error: undefined reference to '_TFV5MySQL5Valueg6doubleGSqSd_'
/home/admin2/Desktop/RS1DataPreparer/Sources/Normalizer.swift:233: error: undefined reference to '_TMV5MySQL5Value'
/home/admin2/Desktop/RS1DataPreparer/Sources/Normalizer.swift:233: error: undefined reference to '_TFV5MySQL5Valueg6doubleGSqSd_'
/home/admin2/Desktop/RS1DataPreparer/Sources/Normalizer.swift:234: error: undefined reference to '_TMV5MySQL5Value'
/home/admin2/Desktop/RS1DataPreparer/Sources/Normalizer.swift:234: error: undefined reference to '_TFV5MySQL5Valueg6doubleGSqSd_'
/home/admin2/Desktop/RS1DataPreparer/Sources/Normalizer.swift:246: error: undefined reference to '_TIFC5MySQL10Connection5queryFzT3sqlSS6valuesGSqGSaGSqSS____CS_6ResultA0_'
/home/admin2/Desktop/RS1DataPreparer/Sources/Normalizer.swift:204: error: undefined reference to '_TMO5MySQL10MysqlError'
/home/admin2/Desktop/RS1DataPreparer/Sources/Normalizer.swift:267: error: undefined reference to '_TMO5MySQL10MysqlError'
/home/admin2/Desktop/RS1DataPreparer/Sources/StockData.swift:20: error: undefined reference to '_TMaC5MySQL10Connection'
/home/admin2/Desktop/RS1DataPreparer/Sources/StockData.swift:20: error: undefined reference to '_TFC5MySQL10ConnectionCfT6configCS_16ConnectionConfig_S0_'
/home/admin2/Desktop/RS1DataPreparer/Sources/StockData.swift:29: error: undefined reference to '_TIFC5MySQL10Connection5queryFzT3sqlSS6valuesGSqGSaGSqSS____CS_6ResultA0_'
/home/admin2/Desktop/RS1DataPreparer/Sources/StockData.swift:33: error: undefined reference to '_TFV5MySQL5Valueg7integerGSqSi_'
/home/admin2/Desktop/RS1DataPreparer/Sources/StockData.swift:41: error: undefined reference to '_TMO5MySQL10MysqlError'
/home/admin2/Desktop/RS1DataPreparer/Sources/StockData.swift:102: error: undefined reference to '_TMaC5MySQL10Connection'
/home/admin2/Desktop/RS1DataPreparer/Sources/StockData.swift:102: error: undefined reference to '_TFC5MySQL10ConnectionCfT6configCS_16ConnectionConfig_S0_'
/home/admin2/Desktop/RS1DataPreparer/Sources/StockData.swift:110: error: undefined reference to '_TIFC5MySQL10Connection5queryFzT3sqlSS6valuesGSqGSaGSqSS____CS_6ResultA0_'
/home/admin2/Desktop/RS1DataPreparer/Sources/StockData.swift:115: error: undefined reference to '_TFV5MySQL5Valueg6stringGSqSS_'
/home/admin2/Desktop/RS1DataPreparer/Sources/StockData.swift:150: error: undefined reference to '_TFC5MySQL10ConnectionCfT6configCS_16ConnectionConfig_S0_'
/home/admin2/Desktop/RS1DataPreparer/Sources/StockData.swift:164: error: undefined reference to '_TFV5MySQL5Valueg6stringGSqSS_'
/home/admin2/Desktop/RS1DataPreparer/Sources/StockData.swift:130: error: undefined reference to '_TMO5MySQL10MysqlError'
/home/admin2/Desktop/RS1DataPreparer/Sources/StockData.swift:261: error: undefined reference to '_TMaC5MySQL10Connection'
/home/admin2/Desktop/RS1DataPreparer/Sources/StockData.swift:279: error: undefined reference to '_TFV5MySQL5Valueg7integerGSqSi_'
/home/admin2/Desktop/RS1DataPreparer/Sources/StockData.swift:281: error: undefined reference to '_TFV5MySQL5Valueg6stringGSqSS_'
/home/admin2/Desktop/RS1DataPreparer/Sources/Config.swift:6: error: undefined reference to '_TMaC5MySQL16ConnectionConfig'
/home/admin2/Desktop/RS1DataPreparer/Sources/Config.swift:6: error: undefined reference to '_TIFC5MySQL16ConnectionConfigcFT4hostSS8databaseSS4portVs6UInt324userSS8passwordSS5flagsVS0_5Flags_S0_A1_'
/home/admin2/Desktop/RS1DataPreparer/Sources/Config.swift:6: error: undefined reference to '_TIFC5MySQL16ConnectionConfigcFT4hostSS8databaseSS4portVs6UInt324userSS8passwordSS5flagsVS0_5Flags_S0_A4_'
/home/admin2/Desktop/RS1DataPreparer/Sources/Config.swift:6: error: undefined reference to '_TFC5MySQL16ConnectionConfigCfT4hostSS8databaseSS4portVs6UInt324userSS8passwordSS5flagsVS0_5Flags_S0_'
/home/admin2/Desktop/RS1DataPreparer/Sources/Scorer.swift:36: error: undefined reference to '_TFV5MySQL5Valueg7integerGSqSi_'
/home/admin2/Desktop/RS1DataPreparer/Sources/Scorer.swift:37: error: undefined reference to '_TFV5MySQL5Valueg6stringGSqSS_'
/home/admin2/Desktop/RS1DataPreparer/Sources/Scorer.swift:133: error: undefined reference to '_TFV5MySQL5Valueg7integerGSqSi_'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
<unknown>:0: error: link command failed with exit code 1 (use -v to see invocation)
<unknown>:0: error: build had 1 command failures
error: exit(1): /home/admin2/swift-DEVELOPMENT-SNAPSHOT-2016-06-06-a-ubuntu15.10/usr/bin/swift-build-tool -f /home/admin2/Desktop/RS1DataPreparer/.build/debug.yaml -v
admin2@admin2:~/Desktop/RS1DataPreparer$

**Comment by Zig1375** [comment]
Now the dispatch is not required for the package.
You have no errors in this package...
I renamed the package from MySQL to SwiftMySQL, probably you should to change package name everywhere.

Because your error "undefined reference to 'TFV5MySQL5Valueg7integerGSqSi'"
